# Generated by Django 5.0.6 on 2024-06-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='public_id',
            field=models.PositiveIntegerField(default=21),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
