# Generated by Django 5.0.6 on 2024-06-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_public_id_post_published_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='public_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
