# Generated by Django 5.0.4 on 2024-05-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_search_vector_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
